-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Graphql.InputObject exposing (..)

import Api.Graphql.Interface
import Api.Graphql.Object
import Api.Graphql.Scalar
import Api.Graphql.ScalarCodecs
import Api.Graphql.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


buildConfigurationInput : ConfigurationInputRequiredFields -> ConfigurationInput
buildConfigurationInput required =
    { content = required.content, filename = required.filename }


type alias ConfigurationInputRequiredFields =
    { content : Api.Graphql.ScalarCodecs.Upload
    , filename : String
    }


{-| Type for the ConfigurationInput input object.
-}
type alias ConfigurationInput =
    { content : Api.Graphql.ScalarCodecs.Upload
    , filename : String
    }


{-| Encode a ConfigurationInput into a value that can be used as an argument.
-}
encodeConfigurationInput : ConfigurationInput -> Value
encodeConfigurationInput input =
    Encode.maybeObject
        [ ( "content", (Api.Graphql.ScalarCodecs.codecs |> Api.Graphql.Scalar.unwrapEncoder .codecUpload) input.content |> Just ), ( "filename", Encode.string input.filename |> Just ) ]
