-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Graphql.Object exposing (..)


type Configuration
    = Configuration


type Project
    = Project
