-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Graphql.ScalarCodecs exposing (..)

import Api.Graphql.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Api.Graphql.Scalar.Id


type alias Upload =
    Api.Graphql.Scalar.Upload


codecs : Api.Graphql.Scalar.Codecs Id Upload
codecs =
    Api.Graphql.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecUpload = defaultCodecs.codecUpload
        }
