name: Test

on: push

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres

jobs:
  cli:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        working-directory: apps/cli
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix test

  parsers-mix:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        working-directory: apps/parsers/mix
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix test

  parsers-worker:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/database
      - name: Run Tests
        working-directory: apps/parsers/worker
        run: |
          mix deps.get
          mix test

  registries-hexpm:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        working-directory: apps/registries/hexpm
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix test

  registries-worker:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/database
      - name: Run Tests
        working-directory: apps/registries/worker
        run: |
          mix deps.get
          mix test

  s12y:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/database
      - name: Run Tests
        working-directory: apps/s12y
        run: |
          mix deps.get
          mix test

  web:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    services:
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/database
      - name: Run Tests
        working-directory: apps/web
        run: |
          mix deps.get
          mix test
